name: score-tube

channels:
  - conda-forge

dependencies:
  - python=3.7
  - hug
  - librosa
  - lxml
  - numba
  - numpy
  - jpype1
  - audioread
  - requests
  - pip
  - pip:
    - pydub
    - gunicorn
